### ISSUE TITLE
Support for non-deepcopyable models

### ISSUE THREAD

**Issue by stefan-baumann** [lucidrains/ema-pytorch#6]
Hi there, 

first of all thanks for the really useful library! There is one thing I have run into which I think could be a good addition to the library: as you're aware, some models are not copyable via `copy.deepcopy`. Instead of just raising an Exception, you could also offer users the ability to input a separate model instance, which is then used for the EMA. Then, the parameters can be synced via `module.parameters()`, and later updated as before.
It would be great if you could offer this (or some other alternative) as an option.

Thanks and all the best!

**Comment by ZeroCool940711** [comment]
Any news on this?
I was searching for exactly this issue since Muse uses this library for loading the ema models and the maskgit training is supposed to use the ema model instead of the non-ema model for the VAE, after trying a few things I was not able to get it working so I did a bit of searching and end up here, seems like if we want to train the Maskgit for Muse with the ema VAE we might need to find a way to add support for non-deepcopyable models.

**Comment by lucidrains** [comment]
hey Alejandro

what error are you seeing? I thought all the modules from muse should be deepcopyable?

**Comment by ZeroCool940711** [comment]
oh, nice, will give it a try and see if I can make it work on Muse :)
